package com.manning.blogapps.chapter07;
import com.sun.syndication.feed.synd.*;
import com.sun.syndication.io.WireFeedOutput;
import java.io.PrintWriter;
import java.util.*;

/**
 * Simple example that shows how to generate a feed.
 */
public class GenerateFeed {
 
	public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.out.println("USAGE: GenerateFeed <feed-type>");
            return;
        }
        
        String feedType = args[0];
        
        SyndFeed feed = new SyndFeedImpl();                       //|#1
        feed.setTitle("Example feed");                            //|#2
        feed.setLink("http://example.com/feeds/blog1");
        feed.setLanguage("en");                             
        feed.setDescription("Example feed generated by ROME");
        feed.setUri("http://example.com/feeds/blog1");            //|#3
        feed.setPublishedDate(new Date());                        //|#4
        
        SyndLink selfLink = new SyndLinkImpl();                   //|#5
        selfLink.setHref("http://example.com/feeds/blog1.xml");
        selfLink.setRel("self");
        feed.setLinks(Collections.singletonList(selfLink));
        
        SyndEntry entry1 = new SyndEntryImpl();
        entry1.setUri("http://example.com/blog/entry1.html");     //|#6
        entry1.setTitle("Entry1");
        entry1.setLink("http://example.com/blog/entry1.html");
        entry1.setPublishedDate(new Date());
        entry1.setUpdatedDate(new Date());                        //|#7
        entry1.setAuthor("Nina");                                 //|#8
        
        SyndContent desc1 = new SyndContentImpl();                 //|#9
        desc1.setValue("Description for test entry #1");
        entry1.setDescription(desc1);
        
        SyndContent content1 = new SyndContentImpl();             //|#10
        content1.setValue("Content for test entry #1");
        entry1.setContents(Collections.singletonList(content1));
        
        List entries = new ArrayList();                           //|#11
        entries.add(entry1);
        feed.setEntries(entries);
        
        WireFeedOutput out = new WireFeedOutput();
        out.output(feed.createWireFeed(feedType),                 //|#12
                new PrintWriter(System.out));
    }
	
}
