/*
 * Copyright 2005-2006, Dave Johnson
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.manning.blogapps.chapter10.blogclientui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.net.MalformedURLException;
import java.util.Iterator;
import java.util.List;

import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import com.manning.blogapps.chapter10.blogclient.Blog;
import com.manning.blogapps.chapter10.blogclient.BlogConnection;
import com.manning.blogapps.chapter10.blogclient.BlogConnectionFactory;

/**
 * Simple Swing-based blog client with tabbed UI.
 * @author David M Johnson
 */
public class BlogClientFrame extends javax.swing.JFrame {
 
	private BlogConnection blogConn = null;
    private Blog           blog = null;
    private String         userName = null;
    private String         password = null;
    private String         url = null;
    private String         type = null;
    
    private com.manning.blogapps.chapter10.blogclientui.BlogClientPanel mBlogClientPanel;
    private com.manning.blogapps.chapter10.blogclientui.BlogEntriesPanel mBlogEntriesPanel;
    
    public BlogClientFrame(String userName, String password, String url, String type) {
        this.userName = userName;
        this.password = password;
        this.url = url;
        this.type = type;
        initComponents();
        
        try {
            initBlogClientLib();
            initBlogClientUI();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
        mBlogEntriesPanel.setBlog(blog);
        mBlogClientPanel.setBlog(blog);
        
        mBlogEntriesPanel.setBlogClientFrame(this);
        mBlogClientPanel.setBlogClientFrame(this);
        
        mTabbelPane.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                JTabbedPane pane = (JTabbedPane)evt.getSource();
                BlogClientTab tab = (BlogClientTab)pane.getSelectedComponent();
                tab.onSelected();
            }        
        });
        mStatusLabel.setText("Working In");
        Iterator allblogs = blogConn.getBlogs().iterator();
        while (allblogs.hasNext()) {
            mBlogCombo.addItem(allblogs.next());
        }
        mBlogCombo.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                blog = (Blog)mBlogCombo.getSelectedItem();
                mBlogEntriesPanel.setBlog(blog);
                mBlogClientPanel.setBlog(blog);
            } 
        });
        Dimension ssize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(
           (ssize.width/2) - (this.getSize().width/2),
           (ssize.height/2) - (this.getSize().height/2) );
    }
    
    private void initBlogClientUI() throws Exception  {
        mBlogClientPanel = new com.manning.blogapps.chapter10.blogclientui.BlogClientPanel();
        mBlogClientPanel.setBlogClientFrame(this); 
        mBlogEntriesPanel = new com.manning.blogapps.chapter10.blogclientui.BlogEntriesPanel();
        mTabbelPane.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        mTabbelPane.addTab("Edit Entry", mBlogClientPanel);
        mTabbelPane.addTab("Entries", mBlogEntriesPanel);
        pack();
    }
    
    private void initBlogClientLib() throws Exception  {
        blogConn = newBlogConnection(url, userName, password, type);
        List blogs = blogConn.getBlogs();
        if (blogs.size() > 0) {
            blog = (Blog)blogs.get(0); // start up with first blog
        }
    }
    
    protected BlogConnection newBlogConnection(
            String url, String userName, String password, String type) 
        throws MalformedURLException, Exception {
        if (type.equals("Atom")) {
            return BlogConnectionFactory.getBlogConnection("atom", url, userName, password);
        }
        return BlogConnectionFactory.getBlogConnection("metaweblog", url, userName, password);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mTabbelPane = new javax.swing.JTabbedPane();
        mStatusPanel = new javax.swing.JPanel();
        mStatusLabel = new javax.swing.JLabel();
        mBlogCombo = new javax.swing.JComboBox();

        mMenu.setText("Menu");
        jMenuBar1.add(mMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RSS and Atom in Action - Blog Client");
        mTabbelPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(mTabbelPane, java.awt.BorderLayout.CENTER);

        mStatusLabel.setText("<no server>");
        mStatusPanel.add(mStatusLabel);

        mStatusPanel.add(mBlogCombo);

        getContentPane().add(mStatusPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox mBlogCombo;
    private javax.swing.JMenu mMenu;
    private javax.swing.JLabel mStatusLabel;
    private javax.swing.JPanel mStatusPanel;
    private javax.swing.JTabbedPane mTabbelPane;
    // End of variables declaration//GEN-END:variables

    public void loadEntry(String id) {
        mTabbelPane.setSelectedComponent(mBlogClientPanel);
        mBlogClientPanel.loadEntry(id);    
        mBlogCombo.setEnabled(false);
    }
    
    public void reset() {
        mBlogCombo.setEnabled(true);
    }
    
}
